"""Write a generated dataset to disk as Parquet or CSV."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from .config import GeneratorConfig
from .generator import RetailDataset

SYNTHETIC_NOTICE = (
    "SYNTHETIC DATA. Generated by retail-analytics-dashboard/data_gen for demos and "
    "testing. It does not describe any real business, store, product or person."
)


def write_dataset(ds: RetailDataset, out_dir: str | Path, cfg: GeneratorConfig,
                  fmt: str = "parquet") -> dict[str, Path]:
    if fmt not in ("parquet", "csv"):
        raise ValueError("fmt must be 'parquet' or 'csv'")
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    paths: dict[str, Path] = {}
    for name, df in ds.tables().items():
        path = out / f"{name}.{fmt}"
        if fmt == "parquet":
            df.to_parquet(path, index=False)
        else:
            df.to_csv(path, index=False)
        paths[name] = path
    manifest = {
        "notice": SYNTHETIC_NOTICE,
        "synthetic": True,
        "format": fmt,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "config": cfg.to_dict(),
        "row_counts": ds.row_counts(),
    }
    (out / "_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    (out / "README.txt").write_text(SYNTHETIC_NOTICE + "\n")
    return paths
